# config/packages/security.yaml
security:
    # Utilisation des password_hashers au lieu des encoders dans Symfony 5.3+
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: users_in_database
            lazy: true
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email    # Utilisation de 'email' comme identifiant
                password_parameter: _password
                csrf_token_id: authenticate  # Identifiant unique pour le token CSRF
                csrf_parameter: _csrf_token  # Nom du paramètre CSRF dans le formulaire
                enable_csrf: true            # Activation de la protection CSRF
                default_target_path: profile_index
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
