# config/packages/security.yaml

security:
    password_hashers:
        App\Entity\User:
            algorithm: argon2id
            memory_cost: 1024
            time_cost: 2

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_token_id: authenticate
                username_parameter: _username
                password_parameter: _password
            logout:
                path: app_logout
                target: app_home

            # Limitation des tentatives de connexion (Login Throttling)
            login_throttling:
                max_attempts: 5

    access_control:
        - { path: ^/admin/user, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
