framework:
    default_locale: fr  # Définit le français comme langue par défaut
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr  # Pas de fallback en anglais, seulement le français
